from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "D-Engine_Handbook.md"
DEST = ROOT / "Docs" / "handbook" / "index.md"

BANNER = (
    "> This page is generated from `D-Engine_Handbook.md`.\n"
    "> Do not edit this file manually. Edit the repository root handbook and run `python tools/docs_sync.py`.\n\n"
)

ANCHOR_FIXUPS = {
    "#17-roadmap-two-tracks-sdk-stability--crowd-slice": "#17-roadmap-two-tracks-sdk-stability-crowd-slice",
}


def main() -> int:
    if not SOURCE.is_file():
        raise FileNotFoundError(f"Missing source handbook: {SOURCE}")

    DEST.parent.mkdir(parents=True, exist_ok=True)
    body = SOURCE.read_text(encoding="utf-8").rstrip()
    for old, new in ANCHOR_FIXUPS.items():
        body = body.replace(old, new)
    DEST.write_text(BANNER + body + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
